<?php
/**
 * Created by PhpStorm.
 * User: yusufshakeel
 * Date: 21/10/17
 * Time: 6:27 PM
 */


class SetUpAndTearDownTest extends PHPUnit_Framework_TestCase
{
    private $stack;

    public function setUp()
    {
        fwrite(STDOUT, __METHOD__ . "\n");
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stack = array();
    }

    public function testEmpty()
    {
        fwrite(STDOUT, __METHOD__ . "\n");
        $this->assertEmpty($this->stack);
    }

    public function testPush()
    {
        fwrite(STDOUT, __METHOD__ . "\n");
        array_push($this->stack, 'foo');
        $this->assertEquals('foo', $this->stack[count($this->stack) - 1]);
    }

    public function testPop()
    {
        fwrite(STDOUT, __METHOD__ . "\n");
        array_push($this->stack, 'foo');
        $this->assertEquals('foo', array_pop($this->stack));
    }

    public function tearDown()
    {
        fwrite(STDOUT, __METHOD__ . "\n");
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
